README file for emacs-perl-devel-cover-overlay

* Name

  emacs-perl-devel-cover-overlay - bindings between emacs and Perl's
  Devel::Cover framework to provide buffer overlays showing coverage
  information.

* Description

  This provides a linkage between emacs and Perl's Devel::Cover
  framework in two parts.

** emacs module

   An emacs module, perl-devcov-overlay.el, that reads JSON data
   provided by the Perl component of this tool, and loads an overlay
   over the current buffer, showing various coverage information.

** Devel::Cover formatting module and script

   A module to be used with Devel::Cover is provided that emits
   information about the coverage database in JSON format.  A script
   will also be provided that allows access to the module from the
   command line (and emacs).

* Source code

  Source code can be found at
  http://github.com/MidLifeXis/emacs-perl-devel-cover-overlay.

  Once this software is at a functional state, I will be providing a
  CPAN module.  It is not, however, available yet.

* Author

  - Brian T. Wightman
  - http://www.wightmanfam.org
  - MidLifeXis@wightmanfam.org
  - MidLifeXis@PerlMonks

* Copyright and License

  Copyright (C) 2012 by Brian T. Wightman

  http://en.wikipedia.org/wiki/MIT_License

  Permission is hereby granted, free of charge, to any person
  obtaining a copy of this software and associated documentation files
  (the "Software"), to deal in the Software without restriction,
  including without limitation the rights to use, copy, modify, merge,
  publish, distribute, sublicense, and/or sell copies of the Software,
  and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.

* Credits

  This is largely inspired by rcov.el, copyright (C) 2008 by Ryan
  Davis, found at http://emacswiki.org/emacs/rcov-overlay.el.

* End of File                                                      :noexport:
